# Generated by Django 4.2.1 on 2023-07-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engine',
            options={'ordering': ['name']},
        ),
    ]
